server:
  port: 3000

spring:
  devtools:
    restart:
      exclude: static/**,public/**,config/application.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/kob?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8